FROM node:20-bullseye-slim

RUN apt-get update && apt-get install -y --no-install-recommends dumb-init

WORKDIR /node-server

RUN npm install express
RUN npm install cors

COPY server.js ./

CMD ["dumb-init", "node", "server.js"]
